name: Cypress Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/*.cy.js
        continue-on-error: true

      - name: Merge reports
        if: always()
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json

      - name: Generate HTML report
        if: always()
        run: |
          npx marge cypress/reports/report.json -o cypress/reports/html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: cypress/reports/html

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - name: Upload Videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: videos
          path: cypress/videos